# Generated by Django 4.0.4 on 2022-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('WorkID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1024)),
                ('tel', models.CharField(max_length=11)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
    ]
