# Generated by Django 4.0.4 on 2022-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1024)),
                ('tel', models.CharField(max_length=11)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('trustworthiness', models.IntegerField(default=100, null=True)),
                ('max_borrow_day', models.IntegerField(default=30, null=True)),
                ('max_borrow_count', models.IntegerField(default=10, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
