# Generated by Django 4.0.4 on 2022-06-03 12:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('WorkID', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1024)),
                ('tel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('ReaderID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('reader_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1024)),
                ('account_status', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('trustworthiness', models.IntegerField(default=100)),
                ('max_borrow_day', models.IntegerField(default=30)),
                ('max_borrow_count', models.IntegerField(default=10)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Reader',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
