# Generated by Django 4.0.4 on 2022-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('WorkID', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1024)),
                ('tel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('ReaderID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reader_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1024)),
                ('account_status', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('trustworthiness', models.IntegerField()),
                ('max_borrow_day', models.IntegerField()),
                ('max_borrow_count', models.IntegerField()),
            ],
            options={
                'db_table': 'Reader',
            },
        ),
    ]
